package Eventhandlers;

public enum Event {
    ANY,
    RECORDING_STARTED,
    RECORDING_STOPPED,
    RECORDING_NEW_CONFIGURATION_AUTO_REMOVE_CHANGED,
    RECORDING_NEW_CONFIGURATION_SAVE_DIR_CHANGED,
    RECORDING_NEW_CONFIGURATION_FPS_CHANGED,
    RECORDING_NEW_CONFIGURATION_FFMPEG_BIN_PATH_CHANGED,
    RECORDING_NEW_CONFIGURATION_MOVIE_NAME_CHANGED
}
